import { DEMO_NOW, DAY_MS } from '../domain/clock.js';

/**
 * Tickets already in flight when the demo starts, so screen 13 shows a working
 * board rather than an empty one. Content follows design/SCREENS.md screen 13.
 *
 * Every seeded ticket carries a `sourceInsightId` like a real one — the board's
 * claim is that each piece of work traces back to the insight that caused it,
 * and a seed that skipped the link would quietly break that claim.
 *
 * Closed tickets carry an `impact`, which is what lets the network prove value
 * with numbers instead of anecdotes.
 */
export function seedTickets({ tenantId = 'nusa-retail', now = DEMO_NOW } = {}) {
  const at = (daysAgo) => new Date(now.getTime() - daysAgo * DAY_MS).toISOString();
  const due = (daysAhead) => new Date(now.getTime() + daysAhead * DAY_MS).toISOString();

  return [
    {
      id: 'T-119',
      tenantId,
      title: 'Audit jadwal restock rak minuman',
      outletId: 'DPK-01',
      outletName: 'Depok Margonda',
      owner: 'Sari Wulandari',
      status: 'baru',
      theme: 'stok-kosong',
      sourceInsightId: 'insight-seed-stok-depok',
      sourceKind: 'agent_run',
      createdBy: 'Agen Reputasi',
      createdAt: at(0.2),
      dueAt: due(5),
      closedAt: null,
      impact: null,
    },
    {
      id: 'T-121',
      tenantId,
      title: 'Tinjau kapasitas parkir motor jam pulang kerja',
      outletId: 'SRP-03',
      outletName: 'Serpong Sektor 7',
      owner: 'Bayu Nugroho',
      status: 'baru',
      theme: 'parkir',
      sourceInsightId: 'insight-seed-parkir-serpong',
      sourceKind: 'agent_run',
      createdBy: 'Agen Reputasi',
      createdAt: at(1),
      dueAt: due(4),
      closedAt: null,
      impact: null,
    },
    {
      id: 'T-118',
      tenantId,
      title: 'Buka kasir kedua 17.00–20.00 selama 2 pekan',
      outletId: 'BKS-02',
      outletName: 'Bekasi Timur',
      owner: 'Dwi Kurnia',
      status: 'dikerjakan',
      theme: 'antrean-kasir',
      sourceInsightId: 'insight-seed-antrean-bekasi',
      sourceKind: 'briefing_decision',
      createdBy: 'manajer@nusaretail.co.id',
      createdAt: at(2),
      dueAt: due(6),
      closedAt: null,
      impact: null,
    },
    {
      id: 'T-116',
      tenantId,
      title: 'Replikasi pola staf floating dari Bogor',
      outletId: null,
      outletName: null,
      owner: 'Ops Excellence',
      status: 'dikerjakan',
      theme: 'antrean-kasir',
      sourceInsightId: 'insight-seed-praktik-bogor',
      sourceKind: 'briefing_decision',
      createdBy: 'manajer@nusaretail.co.id',
      createdAt: at(4),
      dueAt: due(10),
      closedAt: null,
      impact: null,
    },
    {
      id: 'T-120',
      tenantId,
      title: 'Survei lahan kandidat Cibubur Junction',
      outletId: null,
      outletName: null,
      owner: 'Tim Ekspansi',
      status: 'menunggu',
      theme: null,
      sourceInsightId: 'insight-seed-scout-cibubur',
      sourceKind: 'agent_run',
      createdBy: 'Agen Lokasi',
      createdAt: at(3),
      dueAt: due(7),
      closedAt: null,
      impact: 'menunggu anggaran',
    },
    {
      id: 'T-114',
      tenantId,
      title: 'Perbarui SOP penanganan keluhan antrean',
      outletId: null,
      outletName: null,
      owner: 'Ops Excellence',
      status: 'selesai',
      theme: 'antrean-kasir',
      sourceInsightId: 'insight-seed-sop-antrean',
      sourceKind: 'briefing_decision',
      createdBy: 'manajer@nusaretail.co.id',
      createdAt: at(9),
      dueAt: due(-4),
      closedAt: at(5.9),
      impact: 'keluhan antrean turun 18% di 5 cabang',
    },
    {
      id: 'T-109',
      tenantId,
      title: 'Balas 63 review tertunda Bogor',
      outletId: 'BGR-01',
      outletName: 'Bogor Pajajaran',
      owner: 'Intan Permata',
      status: 'selesai',
      theme: null,
      sourceInsightId: 'insight-seed-backlog-bogor',
      sourceKind: 'agent_run',
      createdBy: 'Agen Reputasi',
      createdAt: at(12),
      dueAt: due(-6),
      closedAt: at(10.8),
      impact: 'rating cabang naik 0,2 poin',
    },
  ];
}
